language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - karl@walkow.de
    on_success: always
    on_failure: always
